// Generated by CoffeeScript 1.10.0
(function() {
  var baseObj, funcName, ready, readyEventHandlersInstalled, readyFired, readyList, readyStateChange;

  ready = function() {
    var i, readyFired, readyList;
    if (!readyFired) {
      readyFired = true;
      i = 0;
      while (i < readyList.length) {
        readyList[i].fn.call(window, readyList[i].ctx);
        i++;
      }
      readyList = [];
    }
  };

  readyStateChange = function() {
    if (document.readyState === 'complete') {
      ready();
    }
  };

  funcName = 'docReady';

  baseObj = window;

  readyList = [];

  readyFired = false;

  readyEventHandlersInstalled = false;

  window.document.ready = function(callback, context) {
    if (readyFired) {
      setTimeout(function() {
        callback(context);
      }, 1);
      return;
    } else {
      readyList.push({
        fn: callback,
        ctx: context
      });
    }
    if (document.readyState === 'complete') {
      setTimeout(ready, 1);
    } else if (!readyEventHandlersInstalled) {
      if (document.addEventListener) {
        document.addEventListener('DOMContentLoaded', ready, false);
        window.addEventListener('load', ready, false);
      } else {
        document.attachEvent('onreadystatechange', readyStateChange);
        window.attachEvent('onload', ready);
      }
      readyEventHandlersInstalled = true;
    }
  };

}).call(this);
