outer_path = [
  'login.html',
  'join.html',
  'register.html',
  'create_applyment.html',
  'recover_pwd.html',
]


$(document).ready(function() {
  var member = new SupMember();

  current_path = location.pathname.substr(1)
  
  if(outer_path.indexOf(current_path) < 0 && !member.token()){
    window.location.href = 'login.html';
  }else if(current_path == 'login.html' && member.token()){
    window.location.href = 'index.html';
  }
  
  $('#logout').click(function(e) {
    member.logout()
    .then(function(data) {
      console.log('success:', data);
      window.location.href = 'login.html';
      return data;
    }).catch(function(error) {
      console.log('failed:', error);
    }).finally(function() {
      console.log('finally');
    });
    return false;
  });
  
  $('#login-form').submit(function(e) {
    member.login({
      log: $(this).find('[name="LoginName"]').val(),
      pwd: $(this).find('[name="LoginPwd"]').val()
    }).then(function(data) {
      console.log('success:', data);
      window.location.href = 'index.html';
      return data;
    }).catch(function(error) {
      console.log('failed:', error);
    }).finally(function() {
      console.log('finally');
    });
    return false;
  });
  
  $('#register-form').submit(function(e) {
    member.register({
      log: $(this).find('[name="log"]').val(),
      pwd: $(this).find('[name="pwd"]').val(),
      pwd2: $(this).find('[name="pwd2"]').val(),
      name: $(this).find('[name="name"]').val(),
      email: $(this).find('[name="email"]').val()
    }, function(data) {
      console.log('success:', data);
      window.location.href = 'login.html';
    }, function(error) {
      console.log('failed:', error);
    });
    return false;
  });

  if($('#profile').length > 0 && !member.profile()) {
    member.get_profile(function(data) {
      console.log('success:', data);
      $('#profile').find('.member-login').html(data.login);
      $('#profile').find('.member-name').html(data.name);
    }, function(error) {
      console.log('failed:', error);
    });
  }
  
});

// ---
// generated by coffee-script 1.9.2