$(document).ready(function() {
  "use strict";

  $('.form-mailto').each(function(e){
    var results_success = $(this).find('.results .success');
    var results_error = $(this).find('.results .error');
    results_success.hide();
    results_error.hide();
  });

  $('.form-mailto').submit(function(e) {
    e.preventDefault();
    var results_success = $(this).find('.results .success');
    var results_error = $(this).find('.results .error');

    var opts = {
      app_id: $(this).attr('app-id')
    }
    var type = $(this).attr('type');
    var form_data = {
      fields: $(this).serializeArray(),
      title: $(this).attr('title'),
      type: $(this).attr('type'),
      action: $(this).attr('action'),
    };

    var member = new Skipper(opts);
    var mail_url = member.mailto(form_data);
    window.location.href = mail_url;
    results_success.show();
    return false;
  });

});

// ---
// generated by coffee-script 1.9.2